### ISSUE TITLE
Librimix meta files

### ISSUE THREAD

**Issue by flyjiang92** [mpariente/asteroid#105]
Hi, thank you for sharing these awesome codes!
Could you please tell me how to get the csv files of Librimix?
https://github.com/mpariente/asteroid/blob/68cb7a3a53afc4b509570e71711ed333ab938e42/asteroid/data/librimix_dataset.py#L14
Thank you!
Fei

**Comment by mpariente** [comment]
Hi, 
Thanks for your interest. 
The LibriMix repo was made private for a small while (until we submitted the paper), we'll open it in the next week. 
You'll be able to use the recipe under egs/LibriMix to have the csv files in the right place afterwards. 

Just pinging @JorisCos because he'll open the repo. 
We'll ping you when it's open (and link to the paper on Arxiv as well)

**Comment by flyjiang92** [comment]
Great! Thank you!

**Comment by mpariente** [comment]
Thanks for your patience ! 
The repo is public now, it's [here](https://github.com/JorisCos/LibriMix).
You can follow the stage 0 of the [librimix recipe](https://github.com/mpariente/asteroid/tree/master/egs/librimix/ConvTasNet) to generate the data and the metadata files. Or directly use the script in the LibriMix repo. 

Feel free to close the issue if it's solved

**Comment by flyjiang92** [comment]
Great job! Thanks!
