### ISSUE TITLE
NVIDIA-SMI

### ISSUE THREAD

**Issue by groadabike** [mpariente/asteroid#141]
Hi Manuel,
Are you planning to log the GPU usage during training?
This can be done by using https://github.com/nicolargo/nvidia-ml-py3.
This would help to see the resources without the need for running "watch nvidia-smi" or "nvidia-smi dmon" in a secondary screen.
Thank you

**Comment by mpariente** [comment]
Hi, 
Thanks for opening an issue about that. 
I think I saw other GPU memory loggers in python, and it would be nice indeed. 
Though, I think this would be the role of pytorch lightning rather than Asteroid right? 
I checked master there, but couldn't find if they have the option, I wouldn't surprised if they had. 
Would you like to open an issue there about it?

**Comment by groadabike** [comment]
Hi Manuel,
Yes, you are right, this should be managed by PyTorch lightning. 
The only place where this would make sense is in the system.  
I will open an issue there and let you know what happens.

**Comment by mpariente** [comment]
In the mean time, I'll close this.

**Comment by mpariente** [comment]
I knew I saw that in the past
It has a callback for PytorchLightning
https://github.com/sicara/gpumonitor

**Comment by groadabike** [comment]
Thank you, Manuel
This is exactly what I was thinking about.
