### ISSUE TITLE
about sms_wsj

### ISSUE THREAD

**Issue by KiAlexander** [mpariente/asteroid#145]
why do wsj0 and wsj1 need to be merged? I didn't see wsj1 mentioned in `https://github.com/fgnt/sms_wsj` or in `https://arxiv.org/abs/1910.13934`, 
so how to generate sms_wsj dataset if I only have wsj0?

**Comment by mpariente** [comment]
It's mentionned in the abstract of the paper ("WSJ0+1").
You can't generate SMS_WSJ without WSJ1.
Can I suggest that you have a look at Kinect-WSJ which is based on WSJ0 and CHIME5, also multichannel with speech mixtures in noise.

cc @jensheit who is one of the authors, and the one who implemented the recipe in Asteroid.

**Comment by jensheit** [comment]
When creating this database, we did not consider groups who only have the rights to wsj0 but not to wsj1.
One of our criticism regarding other source separation databases was that they do not allow for acoustic model training because of small training set and low variability.
Using both databases gives us a larger number of speaker and utterances to chose from and allows for a large enough training dataset to train a strong acoustic model.

**Comment by KiAlexander** [comment]
thx
