### ISSUE TITLE
Need feedback: BaseModel.sample_rate re-design

### ISSUE THREAD

**Issue by mpariente** [mpariente/asteroid#318]
Currently, the `BaseModel` looks something like this. 

```python
class BaseModel(nn.Module):
    def __init__(self):
        super().__init__()

    @property
    def sample_rate(self):
        """Operating sample rate of the model (float)."""
        raise NotImplementedError
```

The interface to child model is good, we have `model.sample_rate` work as expected, and it's nice because it's a property. 

If a user wants to write his own child class of `BaseModel`, it would look like this

```python
class Model(BaseModel):
    def __init__(self, sample_rate):
        super().__init__()
        self._sample_rate = sample_rate
        
    @property
    def sample_rate(self):
        return self._sample_rate
```

which is fine, but not obvious to everybody. 

We could change `BaseModel` to look like this: 
```python
class BaseModel(nn.Module):
    def __init__(self, sample_rate):
        super().__init__()
        self._sample_rate = sample_rate

    @property
    def sample_rate(self):
        return self._sample_rate
```

and inheritance would now look like this: 
```python
class Model(BaseModel):
    def __init__(self, sample_rate):
        super().__init__(sample_rate=sample_rate)
```

which is much more user-friendly. 

What would be the downsides of this? 
@jonashaag @mhu-coder @popcornell @JorisCos feedback appreciated.

**Comment by mhu-coder** [comment]
As every model needs to have `sample_rate` to be easy to use at inference, it makes sense to have it in BaseModel. In this case, I guess, `BaseEncoderMaskerDecoder` needs to change
```diff
- super.__init__()
+ super.__init__(sample_rate=encoder.sample_rate)
```
and none of the models inheriting from `BaseEncoderMaskerDecoder` would need to change IIRC.

However, at the moment, the `sample_rate` attribute points back to the value stored in `Filterbank` which ensures consistency throughout the model. At the moment, `sample_rate` is a public attribute, implying that changing it is fine. If we go forward with adding `sample_rate` to `BaseModel`, would it make sense to make `Filterbank.sample_rate` "private"so that people changing its value would know that they are not supposed to?

**Comment by popcornell** [comment]
IMO i don't see when a user will overwrite without knowing the `sample_rate `attribute. 
He would have to do some monkey patching and the chance is that a user which will try to do some monkey patching will actually know what he is going to do. 
I would keep it as simple as possible. I actually had troubles when trying to implement my own model due to the property tag. 

Python does not directly implement private and public attributes and methods. 
These workarounds, even if they are actually used and legit, are not clear for researchers and people not so familiar with advanced python OOP (myself included sorry). 
Compared to C++ they also look very clumsy IMO.

**Comment by mpariente** [comment]
I agree with Samu, I don't see the use case of changing your sample rate on the way..

**Comment by jonashaag** [comment]
Hmmm... so the reason for making this a property or a read only function was so that you don’t have to duplicate the sample rate attribute if you already have it in the filterbank. And I still think this has at least some value since it’s one fewer place where your values may be wrong if something is not working.

I guess most of the time you will either have a sample rate that is tied to the filterbank or some other part of the model, so in this case the current solution is good. Or you will have a model that’s only ever used with a fixed sample rate anyways, then you can just write `return 16000` in the property definition for example. 

OTOH I also see the point in not using advanced Python concepts in this project if there are other ways to do it. So maybe just having a normal `.sample_rate` attribute is more appropriate.

**Comment by mpariente** [comment]
> I guess most of the time you will either have a sample rate that is tied to the filterbank or some other part of the model

You might have that. In this case, you pass that value to the constructor, and you don't duplicate. 


> So maybe just having a normal .sample_rate attribute is more appropriate.

How do you force child classes to have a simple attribute.

**Comment by mpariente** [comment]
BTW, some raw waveform models can work at all sample rate, without the sample rate being tied to any part of the model, but just to the training data. 
This is a case we cannot neglect, and asking users to write something like this in this case doesn't make sense to me. 

```python
class Model(BaseModel):
    def __init__(self, sample_rate):
        super().__init__()
        self._sample_rate = sample_rate
        
    @property
    def sample_rate(self):
        return self._sample_rate
```

I think using "advanced" Python concepts is fine if it's justified, if it makes things simpler (to review, maintain and use) or brings important/cool functionality. But if there is a simpler way of doing it, without much downsides, which I think is the case here, we should go for it.

**Comment by jonashaag** [comment]
> How do you force child classes to have a simple attribute?

I don’t think you can. You can’t force anything in Python, really, except maybe using abstract base classes and MyPy type checks. ABCs don’t support attributes (only properties) and in MyPy I think it is still under construction. For example Protocols do not support attributes.

If you only want to document the abstract attribute, this is the way to go: https://stackoverflow.com/a/54814371

I think documenting only, and not actually forcing anything, is good enough.
