### ISSUE TITLE
Writing best_k_models.json after every epoch

### ISSUE THREAD

**Issue by masztalskipiotr** [mpariente/asteroid#84]
Hi!

First, I would like to thank you for providing such a great tool for speaker separation research. I love it!
However, I have a slight suggestion. When using the recipes from your `egs` directory, the `best_k_models.json` file gets written only after the whole training is finished. This way you cannot just stop your training earlier and go to the evaluation stage because the json file is needed for it. I suggest modifying the code so that the json file is dumped after the 1st epoch, and then updated after each epoch so that you can interrupt your training and go straight to the evaluation stage.

Cheers

Peter

**Comment by mpariente** [comment]
Hey Peter, 

Thank you very much for your kind words ! 

Thanks for the suggestion. Do you already have a simple way to do that? 
I don't think we have access to the checkpoint callback through `System` so that's not directly obvious to do. I can see several ways to do what you'd like but none of them is the obvious one.

Would you like to give it a try? We could discuss your approach first

**Comment by mpariente** [comment]
@masztalskipiotr, want to give it a try?

**Comment by mpariente** [comment]
There are comments regarding this proposition in #96, just in case.

**Comment by popcornell** [comment]
A way also to do it is to have an optional checkpoint argument in eval.py with name of checkpoint.

**Comment by mpariente** [comment]
Closing this, feel free to re-open
